Write-host"[text]"
Write-host"Hello, i am JavascriptCoder999, i hope you like my webpage"
Write-host"i wanted to say a little text about myself"
Write-host"i like baseball, playing on my trampoline and school holidays"
Write-host"my other hobbies are skateboarding, coding and watching futurama it is good"
Write-host"follow my spotify playlist https://open.spotify.com/playlist/3nAr74WeqQcm7YOpHWkevs"
Write-host"follow me too @ducko'bama_961, also follow my tablet account https://open.spotify.com/user/p00so1ekw0jppvmk792i253hv @ducko'bama_962"
Write-host"i joined in august 2020 on my ducko'bama_961 account"
Write-host"and i joined in september on my ducko'bama_962 account"
